### ISSUE TITLE
Não instala mais pelo pip

### ISSUE THREAD

**Issue by aleprovencio** [avelino/pycorreios#15]
Segue o log do pip:

	/home/xand/.virtualenvs/django-royalnew/bin/pip run on Tue Aug 18 14:40:22 2015
	Downloading/unpacking pycorreios

	  Getting page https://pypi.python.org/simple/pycorreios/
	  URLs to search for versions for pycorreios:
	  * https://pypi.python.org/simple/pycorreios/
	  Analyzing links from page https://pypi.python.org/simple/pycorreios/
	    Skipping link https://pypi.python.org/packages/2.6/p/pycorreios/pycorreios-0.1-py2.6.egg#md5=90d05cfd9ab1d524aabdb0927f52d2f2 (from https://pypi.python.org/simple/pycorreios/); unknown archive format: .egg
	    Skipping link https://pypi.python.org/packages/2.7/p/pycorreios/pycorreios-0.1.1-py2.7.egg#md5=e3fbea2f9dd6718b1732b846ac13d26d (from https://pypi.python.org/simple/pycorreios/); unknown archive format: .egg
	  Could not find any downloads that satisfy the requirement pycorreios

	Cleaning up...

	  Removing temporary dir /home/xand/.virtualenvs/django-royalnew/build...
	No distributions at all found for pycorreios

	Exception information:
	Traceback (most recent call last):
	  File "/home/xand/.virtualenvs/django-royalnew/local/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
	    status = self.run(options, args)
	  File "/home/xand/.virtualenvs/django-royalnew/local/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
	    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
	  File "/home/xand/.virtualenvs/django-royalnew/local/lib/python2.7/site-packages/pip/req.py", line 1085, in prepare_files
	    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
	  File "/home/xand/.virtualenvs/django-royalnew/local/lib/python2.7/site-packages/pip/index.py", line 265, in find_requirement
	    raise DistributionNotFound('No distributions at all found for %s' % req)
	DistributionNotFound: No distributions at all found for pycorreios

**Comment by avelino** [comment]
Se você puder corrigir e manda PR sera muito bem vindo!

**Comment by aleprovencio** [comment]
OK, assim que possível mando o PR

**Comment by aleprovencio** [comment]
@avelino, desculpe a minha demora! Você ainda aceitaria o PR? Tem interesse em manter o projeto?

**Comment by avelino** [comment]
aceito sim, só manda

**Comment by aleprovencio** [comment]
@avelino, quando vi que consigo instalar o pycorreios com `pip install git+https://github.com/avelino/pycorreios.git` olhei de novo o log de erros do pip e vi que o problema está realmente com o arquivo do pypi. Seria questão de fazer um novo upload do arquivo correto?

**Comment by avelino** [comment]
gerado novo build 0.1.2 https://pypi.python.org/pypi/pycorreios
